# Generated by Django 5.1.3 on 2024-11-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nicName',
            new_name='nicname',
        ),
    ]
